# Generated by Django 3.1.7 on 2021-03-19 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificado',
            name='documentoDatos',
            field=models.FileField(blank=True, null=True, upload_to='archivos'),
        ),
    ]
