# Generated by Django 3.1.7 on 2021-03-19 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_certificado_documentodatos'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificado',
            name='coordenadaX',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='certificado',
            name='coordenadaY',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='certificado',
            name='isCertificado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='certificado',
            name='isPost',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='certificado',
            name='tipoLetra',
            field=models.FileField(blank=True, null=True, upload_to='archivos'),
        ),
    ]
