# Generated by Django 3.1.7 on 2021-03-22 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210319_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificado',
            name='colorTexto',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='certificado',
            name='tamanioTexto',
            field=models.IntegerField(default=11),
        ),
    ]
