# Generated by Django 3.1.7 on 2021-03-24 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210322_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivosGenerados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreID', models.TextField()),
                ('docGenerado', models.FileField(blank=True, null=True, upload_to='generadosAutomaticos')),
            ],
        ),
    ]
