# Generated by Django 3.1.7 on 2021-03-24 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_archivosgenerados'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificado',
            name='archivoRAR',
            field=models.FileField(blank=True, null=True, upload_to='archivos'),
        ),
    ]
